### ISSUE TITLE
Milestone 0.1.0

### ISSUE THREAD

**Issue by igoogolx** [Future-Scholars/paperlib-ai-chat-extension#12]
我想开始为下一个大版本计划一些工作:

- [x] 代码重构，拆分组件
- [x] 引入 pinia，增强状态管理
- [x] 基于 pinia ，支持多会话和消息历史记录

我正在进行第一步。另外，我目前有时间可以参与 paperlib 的开发，所以有其他 issue 也可以给我。

**Comment by igoogolx** [comment]
Hi，相关功能我已经实现了。除了以上的，还一起支持了消息历史记录持久化。

**Comment by igoogolx** [comment]
有一个问题需要帮忙确认：我们需要一个 paper 的 id 和消息关联起来，我是通过以下方式获取的，我不确定这种方式是否可靠，因为和  `_id ` 的 TS 类型定义是违背的。

```
 curConversationId.value = paperEntity._id as string;
```

**Comment by GeoffreyChen777** [comment]
paperEntity._id 类型有的地方是 ObjectId， 有的地方是 string。这两个都可以接受，因为在最终数据库那里，做了强制转换为 ObjectId。

https://github.com/Future-Scholars/paperlib/blob/6b0e77a3fcae2038819972669550dd7f98205b85/app/repositories/db-repository/paper-entity-repository.ts#L129

**Comment by igoogolx** [comment]
但是我在这里是需要的 string 的，ObjectId 这种类型对于持久化可能会有问题。我在这里拿到的一定是 string 吗？

**Comment by GeoffreyChen777** [comment]
ObjectId 可以直接转化为 string，为了保险，你可以这样:

`id = `${paperEntity._id}`

这样你无论如何都是 string 了。

**Comment by igoogolx** [comment]
另外对于在 ai-chat 里支持“多会话切换”这一点，我觉得没必要。因为现在 ai-chat 和主应用当前查看的 paper 是强关联的，用户切换 paper, ai-chat 就会重新加载。如果我们在 ai-chat 里加上一个 paper selector，总觉得和主应用功能上重复了。

**Comment by GeoffreyChen777** [comment]
所以现在的状态是，支持多会话还是啥

**Comment by igoogolx** [comment]
就是消息历史都会保留，但是用户没有办法看到有那些 paper 是 chat 过的。简单来说，新版的 ai-chat 对于用户而言，UI 上没有任何改变，只是下次进来 chat, 消息历史记录还会在。

**Comment by GeoffreyChen777** [comment]
明白了。

多对话窗口，本质上只对应一个需求，就是用户同时读几篇论文。但是这一般很少见。我认为消息保留就很不错。多对话窗口不是很优先。

除此之外我认为另一个很重要的东西是embedding cache。现在有人反映，打开loading的时间还是长。因此如果只有第一次需要很长时间，之后读取cache会比较理想。

**Comment by igoogolx** [comment]
这个实现起来不难，和消息记录持久化类似，不过缓存的数量可能要控制下，因为一篇 paper 的文本量要大的多，我有空看下。

**Comment by GeoffreyChen777** [comment]
嗯嗯，存个最近几篇应该就够了。存的应该就是每篇文章一个数组。

**Comment by GeoffreyChen777** [comment]
`localforage`这个是必须 dependencies 不能 dev dependencies 是吗？

现在的插件系统，依赖安装路径有问题，导致如果两个插件都安装同一个依赖，会冲突。

因此所有的插件都是用的 dev dependencies，然后bundle到一个js里面去。

我们参考的插件系统实现 已经解决了这个问题，但是我还没在我们插件系统里面实现：
https://github.com/davideicardi/live-plugin-manager/pull/90

如果是必须 dependencies，那我们得先解决 paperlib 的插件系统问题。

**Comment by igoogolx** [comment]
不是的，我忘记这件事了，我会放到 dev dependencies 下面。

**Comment by GeoffreyChen777** [comment]
OK 那没问题
