### ISSUE TITLE
Abstract AI Service

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib-ai-chat-extension#14]
@igoogolx 我想要抽空把 LLM API 相关的东西，比如各种 AI 模型的请求代码，抽出来，做成一个单独的 npm 包。这样 ai-chat 插件和 ai-summary 插件都可以用，就不需要维护两份代码了。你觉得如何。

**Comment by GeoffreyChen777** [comment]
https://github.com/Future-Scholars/llms-api-service

用起来还不错，挺方便。我已经替换了 ai- summary插件，准备把这个ai-chat也换了

**Comment by igoogolx** [comment]
牛的！我在想能不能把 summary 的功能集成到 chat 里，这样就不用维护两个插件了。

**Comment by GeoffreyChen777** [comment]
我考虑过，但是后来觉得，chat太大了，如果每次更新summary，都重新下载整个插件包，太慢了。所以我分开了
