### ISSUE TITLE
Language Matching

### ISSUE THREAD

**Issue by GeoffreyChen777** [Future-Scholars/paperlib-ai-chat-extension#15]
@igoogolx 现在 chat 还有个问题就是语言，如果我用中文问一个英文论文问题，就会出现问题，因为我们是把问题转化为向量，和论文的向量算cosine similarity然后找最大的作为上下文，这中文的向量，我觉得无法和英文的文本向量算相似度。

因此在这个步骤之前，我们还得有一个环节，就是检查两个语言是否匹配，如果不匹配，直接向 LLM 请求先把问题翻译为对应语言，然后再算相似度。

**Comment by igoogolx** [comment]
我觉得语言这个问题有点麻烦，让 LLM 去翻译确实是最简单一种方式，我们只用判断是不是英文，这样对于非中文也可以支持。

**Comment by igoogolx** [comment]
另外我想我们应该提醒用户当前仅支持英文论文，但是支持用任意语言来 chat。

**Comment by GeoffreyChen777** [comment]
有一个node库可以识别文本是什么语言，我回去找找

**Comment by igoogolx** [comment]
我的想法是具体的语言检测就交给 LLM，我们只判断是不是英文，甚至可以用正则表达式暴力判断（26个字母），当然这种方式可能不够准确。

**Comment by GeoffreyChen777** [comment]
llm确实也可以检测，不会有点大炮打蚊子，这块留给我，我抽空弄

**Comment by igoogolx** [comment]
我意思是不用单独多调一次 LLM 去检测，因为本地仅判断是否英文应该简单些。判断以后，我们在最后翻译的时候，prompt 不用指定原始语言，就让 LLM 翻译为英文就可以了，至于原始语言具体是什么就交给 LLM了。

**Comment by igoogolx** [comment]
不好意思，我说的不太清楚，我是这样想的流程：

本地检测是否英文->LLM翻译->计算cosine->LLM解释论文。

肯定是要调用两次 LLM 的。

**Comment by GeoffreyChen777** [comment]
哦哦，我想的是：

npm包检测论文语言和问题语言，不一致的话发送问题到llm翻译为对应论文语言，然后再算cosine。embedding应该是支持所有语言的，因此中文问题和中文文本算相似度没问题。llm也可以翻译大部分语言

**Comment by igoogolx** [comment]
all-MiniLM-L6-v2 只支持英文吧，如果支持所有语言，那模型会很大吧

**Comment by GeoffreyChen777** [comment]
我看了看支持其他语言只是效果没英语那么好

**Comment by GeoffreyChen777** [comment]
搞定了，实现好了。

现在会根据论文语言，翻译后进行consine计算，然后回答问题，也会根据提问的语言进行回复。
