### ISSUE TITLE
use markdown formatting

### ISSUE THREAD

**Issue by tfriedel** [Future-Scholars/paperlib-ai-chat-extension#20]
I just tried the extension, but it outputs markdown and it's all printed without any line breaks which makes it hard to read.

**Comment by GeoffreyChen777** [comment]
yes, that's on the todo list. stay tuned~

**Comment by GeoffreyChen777** [comment]
Hi, this has been implemented.

Update the extension.

NOTE: previous messages are not rendered. All new messages should be rendered now.
